version: "3"
networks:
  app-network:
    driver: bridge
volumes: 
  mysqldata:
   driver: "local"
services:
  mysql:
    container_name: mysql
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    networks:
      - app-network
    ports:
      - "3306:3306"
    volumes: 
      - "~/docker_compartido:/var/www/html/"
      - mysqldata:/var/lib/mysql/
    env_file: .env
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network  
    volumes: 
      - "~/Code:/var/www/html/"
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes: 
      - "~/Code:/var/www/html/"
    ports: 
    - "9000:9000"
    networks:
      - app-network